name: 'Deploy Appwrite Function'
description: 'A simple way to deploy your function to Appwrite'
branding:
  color: 'red'
  icon: 'box'
inputs: 
  endpoint:
    description: 'Your Appwrite endpoint'
  project:
    description: 'The Appwrite project id'
  key:
    description: 'The Appwrite API token'
  code:
    description: 'The directory containing your function'
    default: './'
  locale:
    description: 'Locale'
    default: 'en-US'
  single:
    description: 'Are you deploying a single function?'
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Install Appwrite CLI
      shell: bash
      run: curl -sL https://appwrite.io/cli/install.sh | bash
    - name: Setup Appwrite CLI
      shell: bash
      run: |
        appwrite init \
          --locale='${{ inputs.locale }}' \
          --endpoint='${{ inputs.endpoint }}' \
          --project='${{ inputs.project }}' \
          --key='${{ inputs.key }}'
        appwrite version
    - name: Deploy function
      shell: bash
      run: bash deploy-function.sh ${{ inputs.single }}
